language: php
sudo: false
dist: trusty

php:
  - 7.1

cache:
  directories:
  - vendor

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer update --no-interaction
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpdbg -qrr vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover --coverage-text;
  - vendor/bin/phpcs --standard=PSR2 src tests
  - vendor/bin/php-cs-fixer fix -v --dry-run --allow-risky=yes --using-cache=no

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
